version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "codepipeline-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-109pn79eo70ei"
s3_prefix = "codepipeline-bot"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SlackChannel=\"deployments\" SlackBotName=\"Bender Rodríguez\" SlackBotIcon=\":robot_face:\""

